name: Deploy to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: deploy-gh-pages
  cancel-in-progress: true

env:
  OUTPUT_PATH: ./dist/client
  TARGET_REPO: floatDreamWithSong/floatDreamWithSong.github.io
  HAS_PAGES_TOKEN: ${{ secrets.PAGES_DEPLOY_TOKEN != '' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:static

      - name: Create .nojekyll
        run: touch ${{ env.OUTPUT_PATH }}/.nojekyll

      # optional: if you want deploy gh page in the same repository...
      - name: Deploy ${{ env.OUTPUT_PATH }} to gh-pages
        if: github.event.repository.name == format('{0}.github.io', github.repository_owner)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ env.OUTPUT_PATH }}

      # optional: if you want deploy gh page in another repository...
      - name: Deploy to special repository
        if: env.HAS_PAGES_TOKEN == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          external_repository: ${{ env.TARGET_REPO }}
          publish_branch: main
          publish_dir: ${{ env.OUTPUT_PATH }}
          force_orphan: true